import datetime
import os
import textwrap

# ------------------------------
# MicroCloud customization
import yaml
import sys
from git import Repo
import re
from urllib.parse import urlparse

sys.path.append('_dev/')

with open('../version/version.go') as f:
    match = re.search(r'RawVersion = "([^"]+)"', f.read())
    version = match.group(1) if match else ''
# ------------------------------

# Configuration for the Sphinx documentation builder.
# All configuration specific to your project should be done in this file.
#
# If you're new to Sphinx and don't want any advanced or custom features,
# just go through the items marked 'TODO'.
#
# A complete list of built-in Sphinx configuration values:
# https://www.sphinx-doc.org/en/master/usage/configuration.html
#
# The Sphinx Stack uses the Canonical Sphinx theme to keep all documentation consistent
# and on brand:
# https://github.com/canonical/canonical-sphinx

#######################
# Project information #
#######################

# Project name
project = 'MicroCloud'

# Author name; used in the default copyright statement in the page footer
author = 'Canonical Ltd.'

# The year in the copyright statement
copyright = '2014-%s AGPL-3.0, %s' % (datetime.date.today().year, author)

# Sidebar documentation title
# To disable the title, set to an empty string.
html_title = project + ' documentation ' + version

# Documentation website URL
version_slug = f'{os.environ.get("READTHEDOCS_VERSION", "local")}'
slug = 'microcloud/docs'
html_baseurl = f'https://canonical.com/microcloud/docs/{version_slug}/'

# OpenGraph metadata used for social sharing previews
ogp_site_url = html_baseurl

# Preview name of the documentation website
ogp_site_name = html_title

# Preview image URL
ogp_image = f'https://canonical.com/microcloud/docs/{version_slug}/_static/microcloud_tag.png'

# Product favicon; shown in bookmarks, browser tabs, etc.
html_favicon = '_static/favicon.png'

# Dictionary of values to pass into the Sphinx context for all pages:
# https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_context
html_context = {
    # Product page URL; can be different from product docs URL
    'product_page': 'canonical.com/microcloud',
    # Product tag image; the orange part of your logo, shown in the page header
    'product_tag': '_static/microcloud_tag.png',
    # Your Discourse instance URL
    'discourse': 'https://discourse.ubuntu.com/c/lxd/microcloud/',
    'discourse_prefix': {
        'ubuntu': 'https://discourse.ubuntu.com/t/',
        'lxc': 'https://discuss.linuxcontainers.org/t/',
    },
    # Your Mattermost channel URL
    'mattermost': '',
    # Your Matrix channel URL
    'matrix': '',
    # Your documentation GitHub repository URL If set, links for viewing the
    # documentation source files and creating GitHub issues are added at the bottom of
    'github_url': 'https://github.com/canonical/microcloud',
    # Docs branch in the repo; used in links for viewing the source files
    'repo_default_branch': 'main',
    # Docs location in the repo; used in links for viewing the source files
    'repo_folder': '/doc/',
    # Enables listing contributors on individual pages
    # This feature is deprecated and will be removed in the future
    'display_contributors': False,
    # Required for feedback button
    'github_issues': 'enabled',
    # Passes the top-level 'author' value to the theme
    "author": author,
    # Documentation license information
    "license": {
        # TODO: Specify your project's license.
        # For the name, we recommend using the standard shorthand identifier from
        # https://spdx.org/licenses
        "name": "",
        # TODO: Link directly to your project's license statement.
        "url": "",
    },
    # ------------------------------
    # MicroCloud customization
    'sequential_nav': 'both',
    # ------------------------------
}

html_extra_path = ['_extra']

# Enables the pencil icon to edit pages on GitHub, shown at the top of each page
html_theme_options = {
    'source_edit_link': html_context['github_url']
}

#######################
# Sitemap configuration: https://sphinx-sitemap.readthedocs.io/
#######################

# sphinx-sitemap uses html_baseurl (set earlier in this file) to generate the full URL for each page:

sitemap_url_scheme = '{link}'

# Include `lastmod` dates in the sitemap:
sitemap_show_lastmod = True

# Exclude generated pages from the sitemap:
sitemap_excludes = [
    '404/',
    'genindex/',
    'search/',
]

# Add more pages to sitemap_excludes if needed. Wildcards are supported.
# For example, to exclude module pages generated by autodoc, add '_modules/*'.

#######################
# Template and asset locations
#######################

html_static_path = ['_static']


#############
# Redirects #
#############

# Add redirects to the 'redirects.txt' file
# https://sphinxext-rediraffe.readthedocs.io/en/latest/

# To set up redirects in the Read the Docs project dashboard:
# https://docs.readthedocs.io/en/stable/guides/redirects.html

rediraffe_redirects = 'redirects.txt'

# Strips '/index.html' from destination URLs when building with 'dirhtml'
rediraffe_dir_only = True

############################
# sphinx-llm configuration #
############################

# This description is included in llms.txt to provide some initial context for your
# product docs.
# TODO: Add a description in the form "This is the documentation for <product name>,
# <first sentence of home page>".
llms_txt_description = textwrap.dedent(
    """\
    This is the documentation for the Sphinx Stack, a template repository that helps you
    set up, build, and publish Sphinx documentation.
    """
)

# The base URL for references built by sphinx-markdown-builder.
if os.environ.get("READTHEDOCS"):
    markdown_http_base = html_baseurl

###########################
# Link checker exceptions #
###########################

# Always ignore these links
linkcheck_ignore = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    # These links may fail from time to time
    'https://ceph.io',
    # Rejects us always with a "Connection aborted"
    r'https://charmhub\.io/.*',
    # Cloudflare protection on SourceForge domains often block linkcheck
    r'https://.*\.sourceforge\.(net|io)/.*',
    # These links often fail due to infra issues or protection measures 
    r'https://ubuntu\.com.*',
    r'https://canonical\.com.*',
    r'https://snapcraft\.io.*',
    # Ignore so that we can link change log in release notes before a release is ready
    r'https://github\.com/canonical/microcloud/compare.*',
]

# Pages on which to ignore anchors (check the link without the anchor)
linkcheck_anchors_ignore_for_url = [
    r'https://snapcraft\.io/docs/.*',
    r'https://github\.com/.*',
    r'https://charmhub\.io/.*',
]

# Increase linkcheck rate limit timeout max, default when unset is 300
# https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-linkcheck_timeout
linkcheck_rate_limit_timeout = 600

# Increase linkcheck retries, default when unset is 1
# https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-linkcheck_retries
linkcheck_retries = 3

# Increase the duration, in seconds, that the linkcheck builder will wait for a response after each hyperlink request.
# Default when unset is 30
# https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-linkcheck_timeout
linkcheck_timeout = 45


########################
# Configuration extras #
########################

# Custom MyST syntax extensions; see
# https://myst-parser.readthedocs.io/en/latest/syntax/optional.html
# NOTE: By default, the following MyST extensions are enabled:
#   - substitution
#   - deflist
#   - linkify
# myst_enable_extensions = set()

# Custom Sphinx extensions; see
# https://www.sphinx-doc.org/en/master/usage/extensions/index.html
extensions = [
    'canonical_sphinx',
    'notfound.extension',
    'sphinx_design',
    'sphinx_rerediraffe',
    "sphinx_reredirects",
    'sphinx_tabs.tabs',
    'sphinxcontrib.jquery',
    'sphinxext.opengraph',
    "sphinx_config_options",
    "sphinx_contributor_listing",
    "sphinx_filtered_toctree",
    "sphinx_llm.txt",
    'sphinx_related_links',
    'sphinx_roles',
    'sphinx_terminal',
    "sphinx_ubuntu_images",
    'sphinx_youtube_links',
    'sphinxcontrib.cairosvgconverter',
    'sphinx_last_updated_by_git',
    'sphinx.ext.intersphinx',
    'sphinx_sitemap',
    'myst_parser',
]

# Excludes files or directories from processing
exclude_patterns = [
    '_build',
    'Thumbs.db',
    '.DS_Store',
    '.venv',
    'reference/release-notes/release-notes-template.md',
    '_dev',
    'README.md',
]

# Adds custom CSS files, located remotely or in 'html_static_path'.
html_css_files = [
    'https://assets.ubuntu.com/v1/d86746ef-cookie_banner.css',
]

# Adds custom JavaScript files, located remotely or in 'html_static_path'.
html_js_files = [
    'https://assets.ubuntu.com/v1/287a5e8f-bundle.js',
    'js/rtd-versions-flyout.js',
    "js/overwrite_links.js",
]

# Feedback button at the top; enabled by default
# TODO: Disable the button if your project is unsuitable for public feedback.
# disable_feedback_button = True

# Your manpage URL
# TODO: To enable manpage links, uncomment and replace {codename} with required
#       release, preferably an LTS release (e.g. noble). Do *not* substitute
#       {section} or {page}; these will be replaced by sphinx at build time
#
# NOTE: If set, adding ':manpage:' to an .rst file
#       adds a link to the corresponding man section at the bottom of the page.
# manpages_url = 'https://manpages.ubuntu.com/manpages/{codename}/en/' + \
#     'man{section}/{page}.{section}.html'

# Specifies a reST snippet to be prepended to each .rst file
# This defines a :center: role that centers table cell content.
# This defines a :h2: role that styles content for use with PDF generation.
rst_prolog = """
.. role:: center
   :class: align-center
.. role:: h2
    :class: hclass2
.. role:: woke-ignore
    :class: woke-ignore
.. role:: vale-ignore
    :class: vale-ignore
"""

# Configuration for Intersphinx projects

intersphinx_mapping = {
    'lxd': ('https://canonical.com/lxd/docs/latest/', None),
    'microceph': ('https://canonical.com/ceph/docs/latest/', None),
    'microovn': ('https://ubuntu.com/docs/microovn/latest/', None),
    'ceph': ('https://docs.ceph.com/en/latest/', None),
    'snap': ('https://snapcraft.io/docs/', None),
}

# ------------------------------
# MicroCloud customization beneath this line

# Load substitutions from YAML file
if os.path.exists('./reuse/substitutions.yaml'):
    with open('./reuse/substitutions.yaml', 'r') as fd:
        myst_substitutions = yaml.safe_load(fd.read())

# Use custom 404 page text
notfound_context = {
    'title': 'Page not found',
    'body': '<p><strong>Sorry, but the documentation page that you are looking for was not found.</strong></p>\n\n<p>Documentation changes over time, and pages are moved around. We try to redirect you to the updated content where possible, but unfortunately, that didn\'t work this time (maybe because the content you were looking for does not exist in this version of the documentation).</p>\n<p>You can try to use the navigation to locate the content you\'re looking for, or search for a similar page.</p>\n',
}

# SwaggerUI configuration
if os.environ.get('READTHEDOCS'):
    swagger_url_scheme = '/microcloud/latest/api/#{{path}}'
else:
    swagger_url_scheme = '/api/#{{path}}'

myst_url_schemes = {
    'http': None,
    'https': None,
    'swagger': swagger_url_scheme,
}

# Download and link swagger-ui files
if not os.path.isdir('_dev/deps/swagger-ui'):
    Repo.clone_from('https://github.com/swagger-api/swagger-ui', '_dev/deps/swagger-ui', depth=1)

os.makedirs('_static/swagger-ui/', exist_ok=True)

if not os.path.islink('_static/swagger-ui/swagger-ui-bundle.js'):
    os.symlink('../../_dev/deps/swagger-ui/dist/swagger-ui-bundle.js', '_static/swagger-ui/swagger-ui-bundle.js')
if not os.path.islink('_static/swagger-ui/swagger-ui-standalone-preset.js'):
    os.symlink('../../_dev/deps/swagger-ui/dist/swagger-ui-standalone-preset.js', '_static/swagger-ui/swagger-ui-standalone-preset.js')
if not os.path.islink('_static/swagger-ui/swagger-ui.css'):
    os.symlink('../../_dev/deps/swagger-ui/dist/swagger-ui.css', '_static/swagger-ui/swagger-ui.css')

# Version label shown in the RTD flyout next to "default", in parentheses.
# Set the FLYOUT_DEFAULT_VERSION_LABEL environment variable in the RTD project dashboard.
html_context['flyout_default_version_label'] = os.environ.get('FLYOUT_DEFAULT_VERSION_LABEL', '')
